import 'package:line_awesome_flutter/line_awesome_flutter.dart';
import 'package:scavenger_hunt_bingo/widgets/icon-images.dart';

class Resources {
  static final List<String> city = [
    "Sidewalk",
    "Road",
    "Car",
    "Truck",
    "Van",
    "Bicycle ",
    "Person walking ",
    "Stop sign",
    "Traffic lights",
    "Grass",
    "Hedge",
    "House",
    "Garage ",
    "Garden",
    "Mailbox",
    "No Parking sign",
    "Utility box ",
    "Street light",
    "Street Name sign",
    "Cat",
    "Dog",
    "House with shutters ",
    "Brown roof",
    "Gray roof",
    "Blue roof",
    "Black roof",
    "Red bricks",
    "Brown bricks",
    "White door",
    "Brown door",
    "Blue door"
  ];

  static final List<String> trail = [
    "walking bird",
    "Bird nest",
    "Butterfly ",
    "Dragonfly ",
    "Mosquito ",
    "Pine tree",
    "Cedar tree",
    "Birch tree",
    "Maple tree",
    "Y shaped branch",
    "Tree stump",
    "Fallen branch",
    "Moss",
    "Flat rock",
    "Round rock",
    "Rock with sparkles",
    "Large rock",
    "Pebbles",
    "Bench",
    "Garbage can",
    "Pond",
    "Fence",
    "Sign",
    "Fallen leaves",
    "Footprint",
    "Mud"
  ];
  static final indoors = [
    "shelf",
    "door knob",
    "lamp",
    "mirror",
    "window",
    "curtains",
    "chair",
    "table",
    "mat",
    "cupboard",
    "closet",
    "light bulb",
    "light switch",
    "electrical outlet",
    "hinge",
    "picture",
    "painting",
    "counter",
    "stove",
    "oven",
    "towel",
    "book",
    "something black",
    "something blue",
    "something round",
    "something square",
    "something red",
    "jacket",
    "pants",
    "t-shirt",
    "shoes",
    "fridge",
  ];

  static final indoorIcons = [
    IconImages(name: "mug", icon: LineAwesomeIcons.coffee),
    IconImages(name: "book", icon: LineAwesomeIcons.book),
    IconImages(name: "toilet paper", icon: LineAwesomeIcons.toilet_paper),
    IconImages(name: "socks", icon: LineAwesomeIcons.socks),
    IconImages(name: "t-shirt", icon: LineAwesomeIcons.t_shirt),
    IconImages(name: "mitten", icon: LineAwesomeIcons.mitten),
    IconImages(name: "ruler", icon: LineAwesomeIcons.ruler),
    IconImages(name: "tool-box", icon: LineAwesomeIcons.toolbox),
    IconImages(name: "clock", icon: LineAwesomeIcons.clock),
    IconImages(name: "calendar", icon: LineAwesomeIcons.calendar),
    IconImages(name: "scissors", icon: LineAwesomeIcons.cut),
    IconImages(name: "glasses", icon: LineAwesomeIcons.glasses),
    IconImages(name: "paper clip", icon: LineAwesomeIcons.paperclip),
    IconImages(name: "light bulb", icon: LineAwesomeIcons.lightbulb),
    IconImages(name: "plug", icon: LineAwesomeIcons.plug),
    IconImages(name: "bath tub", icon: LineAwesomeIcons.bath),
    IconImages(name: "tv", icon: LineAwesomeIcons.television),
    IconImages(name: "chair", icon: LineAwesomeIcons.chair),
    IconImages(name: "open door", icon: LineAwesomeIcons.door_open),
    IconImages(name: "closed door", icon: LineAwesomeIcons.door_closed),
    IconImages(name: "bed", icon: LineAwesomeIcons.bed),
    IconImages(name: "fan", icon: LineAwesomeIcons.fan),
    IconImages(name: "shower", icon: LineAwesomeIcons.shower),
    IconImages(name: "box", icon: LineAwesomeIcons.box),
    IconImages(name: "utensils", icon: LineAwesomeIcons.utensils),
    IconImages(name: "calculator", icon: LineAwesomeIcons.calculator),
    IconImages(name: "tape", icon: LineAwesomeIcons.tape),
    IconImages(name: "headphones", icon: LineAwesomeIcons.headphones),
    IconImages(name: "envelope", icon: LineAwesomeIcons.envelope)
  ];

  static final cityIcons = [
    IconImages(name: "cat", icon: LineAwesomeIcons.cat),
    IconImages(name: "crow", icon: LineAwesomeIcons.crow),
    IconImages(name: "dog", icon: LineAwesomeIcons.dog),
    IconImages(name: "car", icon: LineAwesomeIcons.car_side),
    IconImages(name: "truck", icon: LineAwesomeIcons.truck),
    IconImages(name: "motorcycle", icon: LineAwesomeIcons.motorcycle),
    IconImages(name: "biking", icon: LineAwesomeIcons.biking),
    IconImages(name: "pickup truck", icon: LineAwesomeIcons.truck_side),
    IconImages(name: "bicycle", icon: LineAwesomeIcons.bicycle),
    IconImages(name: "running", icon: LineAwesomeIcons.running),
    IconImages(name: "walking", icon: LineAwesomeIcons.walking),
    IconImages(name: "flag", icon: LineAwesomeIcons.flag),
    IconImages(name: "newspaper", icon: LineAwesomeIcons.newspaper),
    IconImages(name: "traffic light", icon: LineAwesomeIcons.traffic_light),
    IconImages(name: "shopping bag", icon: LineAwesomeIcons.shopping_bag),
    IconImages(name: "sign", icon: LineAwesomeIcons.sign),
    IconImages(name: "baby carriage", icon: LineAwesomeIcons.baby_carriage),
    IconImages(name: "church", icon: LineAwesomeIcons.church),
    IconImages(name: "cloud", icon: LineAwesomeIcons.cloud),
    IconImages(name: "plane", icon: LineAwesomeIcons.plane),
    IconImages(name: "road", icon: LineAwesomeIcons.road),
    IconImages(name: "sun", icon: LineAwesomeIcons.sun),
    IconImages(name: "trash", icon: LineAwesomeIcons.trash),
    IconImages(name: "bug", icon: LineAwesomeIcons.bug),
    IconImages(name: "door closed", icon: LineAwesomeIcons.door_closed),
    IconImages(name: "door open", icon: LineAwesomeIcons.door_open),
    IconImages(name: "parking", icon: LineAwesomeIcons.parking),
    IconImages(name: "home", icon: LineAwesomeIcons.home),
    IconImages(name: "store", icon: LineAwesomeIcons.store)
  ];

  static final trailIcons = [
    IconImages(name: "paw print", icon: LineAwesomeIcons.paw),
    IconImages(name: "crow", icon: LineAwesomeIcons.crow),
    IconImages(name: "dog", icon: LineAwesomeIcons.dog),
    IconImages(name: "spider", icon: LineAwesomeIcons.spider),
    IconImages(name: "tree", icon: LineAwesomeIcons.tree),
    IconImages(name: "map signs", icon: LineAwesomeIcons.map_signs),
    IconImages(name: "biking", icon: LineAwesomeIcons.biking),
    IconImages(name: "leaf", icon: LineAwesomeIcons.leaf),
    IconImages(name: "footprints", icon: LineAwesomeIcons.shoe_prints),
    IconImages(name: "running", icon: LineAwesomeIcons.running),
    IconImages(name: "walking", icon: LineAwesomeIcons.walking),
    IconImages(name: "seedling", icon: LineAwesomeIcons.seedling),
    IconImages(name: "poop", icon: LineAwesomeIcons.poop),
    IconImages(name: "hiking", icon: LineAwesomeIcons.hiking),
    IconImages(name: "building", icon: LineAwesomeIcons.building),
    IconImages(name: "clouds with sun", icon: LineAwesomeIcons.cloud_with_sun),
    IconImages(name: "wind", icon: LineAwesomeIcons.wind),
    IconImages(name: "water", icon: LineAwesomeIcons.water),
    IconImages(name: "cloud", icon: LineAwesomeIcons.cloud),
    IconImages(name: "plane", icon: LineAwesomeIcons.plane),
    IconImages(name: "road", icon: LineAwesomeIcons.road),
    IconImages(name: "sun", icon: LineAwesomeIcons.sun),
    IconImages(name: "trash", icon: LineAwesomeIcons.trash),
    IconImages(name: "bug", icon: LineAwesomeIcons.bug),
    IconImages(name: "ban", icon: LineAwesomeIcons.ban),
    IconImages(name: "bird", icon: LineAwesomeIcons.dove),
    IconImages(name: "friends", icon: LineAwesomeIcons.user_friends),
  ];
}
