class Resources {
  static final List<String> city = [
    "Sidewalk",
    "Road",
    "Car",
    "Truck",
    "Van",
    "Bicycle ",
    "Person walking ",
    "Stop sign",
    "Traffic lights",
    "Grass",
    "Hedge",
    "House",
    "Garage ",
    "Garden",
    "Mailbox",
    "No Parking sign",
    "Utility box ",
    "Street light",
    "Street Name sign",
    "Cat",
    "Dog",
    "House with shutters ",
    "Brown roof",
    "Gray roof",
    "Blue roof",
    "Black roof",
    "Red bricks",
    "Brown bricks",
    "White door",
    "Brown door",
    "Blue door"
  ];

  static final List<String> trail = [
    "walking bird",
    "Bird nest",
    "Butterfly ",
    "Dragonfly ",
    "Mosquito ",
    "Pine tree",
    "Cedar tree",
    "Birch tree",
    "Maple tree",
    "Y shaped branch",
    "Tree stump",
    "Fallen branch",
    "Moss",
    "Flat rock",
    "Round rock",
    "Rock with sparkles",
    "Large rock",
    "Pebbles",
    "Bench",
    "Garbage can",
    "Pond",
    "Fence",
    "Sign",
    "Fallen leaves",
    "Footprint",
    "Mud"
  ];
  static final indoors = [
    "shelf",
    "door knob",
    "lamp",
    "mirror",
    "window",
    "curtains",
    "chair",
    "table",
    "mat",
    "cupboard",
    "closet",
    "light bulb",
    "light switch",
    "electrical outlet",
    "hinge",
    "picture",
    "painting",
    "countertop",
    "stove",
    "oven",
    "towel",
    "book",
    "something black",
    "something blue",
    "something round",
    "something square",
    "something red",
    "jacket",
    "pants",
    "t-shirt",
    "shoes"
  ];
}
